# Generated by Django 4.0.3 on 2024-02-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
